# 章节二：单变量线性回归

## 模型描述

- 假设函数：h
- 房子大小：x
- 房子售价：y

我们需要找到一个假设函数h来通过房子的面积大小作为输入，判断该房屋的售价。

$ h_\theta(x) = \theta_0 + \theta_1*x $

![](http://andrew-machine-learning.oss-cn-hangzhou.aliyuncs.com/represent_h.png)

## 代价函数（Cost function）

![](http://andrew-machine-learning.oss-cn-hangzhou.aliyuncs.com/20200225213013.png)

![](http://andrew-machine-learning.oss-cn-hangzhou.aliyuncs.com/cost_function.png)

![](http://andrew-machine-learning.oss-cn-hangzhou.aliyuncs.com/20200225224046.png)

$ J(\theta_0, \theta_1) = \frac{1}{2m} \sum_{i=1}^m (h_\theta(x^{(i)})-y^{(i)})^2 $

## 梯度下降（Gradient descent）

梯度下降不仅被用在线性回归上，还被广泛应用于机器学习的众多领域。

$ \theta_j := \theta_j - \alpha \frac{\partial}{\partial\theta_j}J(\theta_0, \theta_1)$


In [1]:
import numpy as np

A = np.array([[1, 2, 3, 4]])
B = np.array([[4, 5, 6, 7]]).T
print(A.T * B)

[[ 4]
 [10]
 [18]
 [28]]


In [17]:
u = np.array([1, 3])
v = np.array([12, 3])
print(np.dot(u, v))
print(np.cross(v, u))

21
33


In [20]:
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
np.dot(B, A)

array([[ 50,  60],
       [114, 140]])

In [2]:
from scipy import linalg

A = np.array([[1, 35, 0], [0, 2, 3], [0, 0, 4]])
B = linalg.inv(A)
B

array([[  1.   , -17.5  ,  13.125],
       [  0.   ,   0.5  ,  -0.375],
       [  0.   ,   0.   ,   0.25 ]])

In [3]:
np.dot(A, B)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])