# 章节三：线性代数回顾

## 矩阵和向量

## 加法和标量乘法

### 加法

两个相同维数的矩阵相加就是将对应位置的矩阵元素相加

$ \begin{bmatrix}
0 & 3 \\
 3 & 0
 \end{bmatrix} +
 \begin{bmatrix}
4 & 3 \\
 2 & 5
 \end{bmatrix} =
 \begin{bmatrix}
4 & 6 \\
 5 & 5
 \end{bmatrix}
$

### 标量乘法

将矩阵中的袁术逐一与标量相乘

$
\begin{bmatrix} 0 & 3 \\ 3 & 0 \end{bmatrix}
\times 4 =
\begin{bmatrix} 0 & 12 \\ 15 & 0 \end{bmatrix}
$

In [2]:
import numpy as np

A1 = np.array([[0, 3], [3, 0]])
B1 = np.array([[4, 3], [2, 5]])
C = A1 + B1
print(C)
print(A1 * 4)

[[4 6]
 [5 5]]
[[ 0 12]
 [12  0]]


## 矩阵向量乘法

$
\begin{bmatrix} 1 & 2 & 1 & 5 \\ 0 & 3 & 0 & 4 \\ -1 & -2 & 0 & 0 \end{bmatrix}
\times \begin{bmatrix} 1 \\ 3 \\ 2 \\ 1 \end{bmatrix} =
\begin{bmatrix} 14 \\ 13 \\ -7 \end{bmatrix}
$

![](http://andrew-machine-learning.oss-cn-hangzhou.aliyuncs.com/20200301011813.png)

In [3]:
A = np.array([[1, 2, 1, 5], [0, 3, 0, 4], [-1, -2, 0, 0]])
B = np.array([[1], [3], [2], [1]])
np.dot(A, B)

array([[14],
       [13],
       [-7]])

In [4]:
A = np.array([[1, 2104], [1, 1416], [1, 1534], [1, 852]])
B = np.array([[-40], [0.25]])
np.dot(A, B)

array([[486. ],
       [314. ],
       [343.5],
       [173. ]])

## 矩阵乘法

![](http://andrew-machine-learning.oss-cn-hangzhou.aliyuncs.com/20200301113415.png)

![](http://andrew-machine-learning.oss-cn-hangzhou.aliyuncs.com/20200301114123.png)

In [5]:
A = np.array([[1, 2104], [1, 1416], [1, 1534], [1, 852]])
B = np.array([[-40, 200, -150], [0.25, 0.1, 0.4]])
np.dot(A, B)

array([[486. , 410.4, 691.6],
       [314. , 341.6, 416.4],
       [343.5, 353.4, 463.6],
       [173. , 285.2, 190.8]])

## 矩阵乘法特征

A是一个 $ m \times n $ 的矩阵，B是一个 $ n \times m $ 的矩阵，k是实数

- $ A \times k = k \times A$
- $ A \times B \neq B \times A $
- $ A \times B \times C = A \times (B \times C) = (A \times B) \times C $

### 单位矩阵

从左上角至右下角的对角线上的元素全为1，其余元素全为0，记作 $ I_{n \times n} $

$ \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{bmatrix} $

- 对于任何矩阵$A$：$ A \times I = I \times A = A $

In [6]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

对于矩阵$A$,存在 $ AA^-1 = A^-1A = I $，则称矩阵 $A^-1$ 为矩阵 $A$ 的逆矩阵。

对于矩阵$A$，交换 $A$ 的行和列，得到 $A$ 的转置矩阵 $A^T$，则称矩阵 $A^T$ 为矩阵 $A$ 的转置矩阵。

例如：

$ A = \begin{bmatrix} 1&2&0\\3&5&9 \end{bmatrix} $
$ A^T = \begin{bmatrix} 1&3\\2&5\\0&9 \end{bmatrix} $



In [27]:
import numpy as np
from scipy import linalg

A = np.array([[3, 4], [2, 16]])
B = linalg.inv(A)
print(B)
print(np.dot(A, B))

[[ 0.4   -0.1  ]
 [-0.05   0.075]]
[[1. 0.]
 [0. 1.]]


In [29]:
# 矩阵A
A = np.array([[1, 2, 0], [3, 5, 9]])
# 矩阵A的转置矩阵
A.T


array([[1, 3],
       [2, 5],
       [0, 9]])